name: KEGM Veri Senkronizasyonu

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Paketleri Yükle
        run: npm install axios cheerio

      - name: Verileri Çek
        run: node scraper.js

      - name: Veriyi Kaydet
        run: |
          git config --global user.name "KEGM Bot"
          git config --global user.email "bot@github.com"
          git add ships.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Gemi listesi güncellendi" && git push)
